development: &development
    developer: true
    base: "http://localhost:3000"
    return_to: "/ingressos/retorno"
    email: rmatuoka@agenciaeconomica.com.br

test:
  <<: *development

production:
  authenticity_token: F22635ADF1214D41A668B8671CCCA3C6
  email: compras@festadasfloresdeatibaia.com.br
  return_to: "http://www.festadasfloresdeatibaia.com.br/ingressos/retorno"
